### ISSUE TITLE
Signalling of Live vs Legacy in EDMarketConnector data export

### ISSUE THREAD

**Issue by Athanasius** [eyeonus/Trade-Dangerous#103]
EDMarketConnector has the option to save "Market data in Trade Dangerous format file" as documented at https://github.com/eyeonus/Trade-Dangerous/wiki/Price-Data

Does TD want to define a way to signal if the data came from the Live or Legacy galaxy ?  I'm just adding support for the Legacy CAPI host/endpoint now, so users of this would have to be careful if they play in both galaxies.

**Comment by eyeonus** [comment]
I'm sorry, I haven't been keeping up with the news, so I don't know about the Live/Legacy thing. LEt me go read up on that real quick.

Currently, the "official" means of obtaining crowd-sourced prices data is by using the eddblink import plugin, which uses the EDDB API files to build TD's database.

The most likely use case for importing .prices files created by EDMC, in my estimation, is a person wanting to import their own data, I'm not aware of people passing around .prices files to each other or posting them online.

If there is a backwards-compatible way to mark legacy prices files as such, that would be ideal, but to be honest I don't even know what the format is because I never deal with them.

When I last played the trading game in ED, I used EDMC to submit the station info to EDDN and ran my eddn-listener to update TD, so I never actually used EDMCs export feature, myself.

TD can be run a multiple databases, so at least for personal-only market data, running TD in ".../EDLive" and ".../EDLegacy" folders depending on which galaxy one is playing in is sufficient to workaround any potential issues.

If crowd-sourced Legacy data becomes a thing (such as if EDDB starts tracking it as well as the Live galaxy), then I'll revisit this.

Thanks for the heads up, I appreciate it.

**Comment by Athanasius** [comment]
> If there is a backwards-compatible way to mark legacy prices files as such, that would be ideal, but to be honest I don't even know what the format is because I never deal with them.

It's the *Trade Dangerous defined* format, as per that link to the TD Wiki within this very repo that I included in OP.  I was asking if *you* wanted to extend that to include an indicator of 'source galaxy'.

> TD can be run on multiple databases, so at least for personal-only market data, running TD in ".../EDLive" and ".../EDLegacy" folders, depending on which galaxy one is playing in, is sufficient to workaround any potential issues.

In that case I'll just consider it as a "user problem" if anyone is actually using TD in that manner.  I'm *almost* tempted to just remove the code and see if anyone screams ;) .
 
> If crowd-sourced Legacy data becomes a thing (such as if EDDB starts tracking it as well as the Live galaxy), then I'll revisit this.

Unlikely.  None of the big sites want the headache of potentially doubling up *all* of the data.  They're all going "Live only".

I'll consider this a non-problem unless and until an EDMC user actually complains/asks.

**Comment by eyeonus** [comment]
> It's the _Trade Dangerous defined_ format, as per that link to the TD Wiki within this very repo that I included in OP. I was asking if _you_ wanted to extend that to include an indicator of 'source galaxy'.

I did not know that, I thought someone else came up with the format.

I guess make the first line be '#!legacy' if it ever becomes needed, but I agree this is most likely a non-problem

**Comment by Athanasius** [comment]
Heh, and I'm at least 2nd generation maintainer of EDMC.

Btw, it's occurred to me that *because* of the Live/Legacy split and the main third-party sites only supporting Live, it's possible there might now be an increase in players interested in such "provide and maintain your own data" tools.  But, yes, let's just leave it up to the users to not make a mess of their own data.

**Comment by eyeonus** [comment]
Mmm, you may be right

Imma mention the multiple database thing in TD thread on the ED forum in hopes that prevents one or more data messes, just 'cause I'm nice like that
