### ISSUE TITLE
PIP package is not up to date

### ISSUE THREAD

**Issue by Hysterikon** [eyeonus/Trade-Dangerous#119]
When installing via pip version 10.13.0 gets installed, somehow the latest two releases are missing.

`pip install --upgrade tradedangerous==10.14.1` results in this error message: 

`ERROR: Could not find a version that satisfies the requirement tradedangerous==10.14.1 (from versions: 10.0.2, 10.0.3, 10.1.0, 10.1.1, 10.1.2, 10.2.0, 10.2.1, 10.2.2, 10.3.0, 10.3.1, 10.4.0, 10.4.1, 10.4.2, 10.4.3, 10.4.4, 10.4.5, 10.4.6, 10.4.7, 10.4.8, 10.5.0, 10.5.1, 10.5.2, 10.5.3, 10.5.4, 10.5.5, 10.5.6, 10.5.7, 10.6.0, 10.6.1, 10.6.2, 10.6.3, 10.7.0, 10.7.1, 10.8.0, 10.8.1, 10.8.2, 10.9.0, 10.9.3, 10.9.4, 10.9.5, 10.9.6, 10.9.7, 10.9.8, 10.10.0, 10.11.0, 10.11.1, 10.11.3, 10.12.0, 10.13.1, 10.13.2, 10.13.4, 10.13.5, 10.13.6, 10.13.7, 10.13.8, 10.13.9, 10.13.10)
ERROR: No matching distribution found for tradedangerous==10.14.1`

**Comment by eyeonus** [comment]
Pypi made 2FA a requirement for doing anything since the last release, and completely changed how to publish so of course they didn't notify me that I'd have to set that up before they'd allow newer versions to be published, the jerks.

Time to commit 50 new changes until one of them finally makes it work again....

**Comment by eyeonus** [comment]
Package is now up to date. Finally.
