### ISSUE TITLE
The search for specific goods generates an error ! Function "buy"

### ISSUE THREAD

**Issue by nepomuk16321** [eyeonus/Trade-Dangerous#153]
![image](https://github.com/eyeonus/Trade-Dangerous/assets/20616775/8f0cd09a-5fd0-43e2-9c3b-33f63449c2e0)

**Comment by kfsone** [comment]
looking

**Comment by kfsone** [comment]
@eyeonus with 
```
python ./trade.py buy -w --near="Amber/Felice Plant" --ly=16.00 --pad=M --planetary=N --fc=N --limit=42 -vv "Bauxite"
```
to enable the full 'rich' error reporting and in a nutshell I appear to have left a trailing comma that turned a string into a tuple.
![image](https://github.com/eyeonus/Trade-Dangerous/assets/323009/1805364e-bc2b-49bd-8aee-ac3f9b5ddaf2)

**Comment by eyeonus** [comment]
How did you enable rich reporting, and how do we make it do that by default? It seems super useful to have it use that on clients' instances so that they can send that rather than the somewhat less informative error message such as @nepomuk16321's

**Comment by kfsone** [comment]
Let me walk myself thru it for synchronization:

tradeenv.py will enable the "tame" version of it:
https://github.com/eyeonus/Trade-Dangerous/blob/release/v1/tradedangerous/tradeenv.py#L31-L34
if you set EXCEPTIONS.
unix-shell: `EXCEPTIONS =1 trade.py makemerich`
powershell: `$env:EXCEPTIONS = 1; trade.py makebillgatesrich` (* I'm actually a powershell user and fan)

and by -w here
https://github.com/eyeonus/Trade-Dangerous/blob/release/v1/tradedangerous/tradeenv.py#L209-L210

https://rich.readthedocs.io/en/latest/traceback.html

apparently they have a print_exception flavor too that lets you target specific exceptions with more detail, so if there's a problem scenario where a particular exception is being triggered in unknown circumstances, just that particular exception can be turned into hyper-spam

I didn't want to enable it by default on you because some pythonistas will  (╯‵□′)╯︵┻━┻ at the sight of their beautified backtrace dark mumbo jumbo. imo they can always get a new one from ikea.

The extreme version is super noisy and spammy and I don't think you want it on by default, and I didn't spend the time to learn how to leverage more fine grained control, but it's enabled by "-w".

**Comment by kfsone** [comment]
if you want to see what it looks like - randomly drop a "raise Exception('you aint seen me')" somewhere in say the buy command and then `trade.py buy -w ...` - just don't expect to be able to find the top ...

**Comment by kfsone** [comment]
[rich](https://rich.readthedocs.io/en/latest/index.html) is seriously f'ing awesome.

**Comment by eyeonus** [comment]
```
[eyeonus@panther Trade-Dangerous]$ EXTENSIONS=1 ./trade.py makemerich
bash: ./trade.py: Permission denied
[eyeonus@panther Trade-Dangerous]$ sudo EXTENSIONS=1 ./trade.py makemerich
[sudo] password for eyeonus: 
sudo: ./trade.py: command not found
[eyeonus@panther Trade-Dangerous]$ ls
CHANGELOG.legacy.md  fix-indent.sh         requirements-publish.txt  tests                    tradedangerous.egg-info
CHANGELOG.md         LICENSE               requirements.txt          tmp                      TradeDangerous.pyproj
CHANGES.txt          pyproject.toml        scripts                   tox.ini                  TradeDangerous.sln
data                 README.md             setup.cfg                 tradedangerous           tradegui.py
docs                 requirements-dev.txt  setup.py                  tradedangerouscrest.ico  trade.py
```

**Comment by eyeonus** [comment]
Um, you meant EXCEPTIONS, didn't you?

**Comment by kfsone** [comment]
yar - I do, sorry. Worse, I retyped EXTENSIONS when I tried to fix it.

**Comment by kfsone** [comment]
I believe this is resolved, @nepomuk16321 ?

**Comment by nepomuk16321** [comment]
Yes, it works again. I still had an error during the first test in which an unknown system was announced.
I then removed this system from the price list. On the second attempt, everything worked without any problems.
The desired list was displayed.
Thank you both for your efforts! :-)
