### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by MarkAusten** [eyeonus/Trade-Dangerous#19]
If I run the command:

`buy --near="Orang/Bessel Gateway" --ly=24 --pad=L --lim=0 -vv -P "Antiquities"`

I get the following error:

`Traceback (most recent call last):`
`[snip]`
`  File "buy_cmd.py", line 245, in run`
`    results.summary.avg = int(avgPrice)`
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

If I change the commodity to something else I do not get that error. For example:

`buy --near="Orang/Bessel Gateway" --ly=24 --pad=L --lim=0 -vv -P "Aquaponic Systems"`

I have not tried this with all the commodities or ships, just a handful and Antiquities is to only one that gives this error although there could be others.

I have the latest TD and updated the DB earlier today.

**Comment by eyeonus** [comment]
Latest data only has one entry for Antiquities, with a buy price of 0 Cr. avgPrice is the result of an SQL query that finds all the listings for the specified item, that have a buy price > 0, averaged. Since there are no listings with a buy price > 0 for this item, it returns nothing.

That's the source of the problem.

It's been fixed.
