### ISSUE TITLE
Not pulling the most profitable and fresh prices/trades

### ISSUE THREAD

**Issue by McRayJason** [eyeonus/Trade-Dangerous#82]
Hello.
First of all I want to thank you for the work you put in this Tool. It is pretty much what i have been looking for that can support FAR jumps with fleet carriers.

However I am either not understanding it, or there is something wrong.

I wanted to check Direct trades to LP 787-52/Tanner Orbital, what would be the most profitable.
![Silver to Tanner Orbital](https://user-images.githubusercontent.com/39248367/103572205-81a06700-4ecc-11eb-8b13-675228e1e177.png)

This gave me I should buy Silver in Slatus/Hadifeld Station. The price when I check Inara for buying Silver from there: 
![Silver Hadfield](https://user-images.githubusercontent.com/39248367/103572317-a7c60700-4ecc-11eb-869c-2a05e8b77ce0.png)
It is 33,961 Cr, with supply of 76k tons. Updated 18 days ago.

But when i check all the Best exports of Silver i see:
![Silver Arimpox](https://user-images.githubusercontent.com/39248367/103572392-c6c49900-4ecc-11eb-95a0-0cdf9543b7f6.png)
There is 3,494 Cr. it has high supply of 3,517 tons, updated 6 minutes ago

So my question is, why is the tool not showing me that i should go and buy it from Arimpox System, since it would be much more profitable. And it has been updated only few minutes ago, whilst Hadfield was 18 days ago.

(I just in case updated the listings, so it would fetch the most current data)

**Comment by eyeonus** [comment]
Unfortunately that's not enough information to know.

Try running it with at least '-v', it might provide enough information to figure it out.

Also, it's helpful to me to put the command in question in the issue report directly, rather than as a screenshot, as that enables me to copy/paste the command to run myself, rather than having to retype it by hand.

I'm looking into it.

**Comment by eyeonus** [comment]
After some investigating, this looks like Inara's fault:

```
Trade-Dangerous\test>trade run --to="LP 787-52/Tanner Orbital" --cap=760 --cr=2015504735 --ly=500.00 --empty=500.0 --direct --pad=ML --progress -vvv
* Hop   1: ....41,377 origins
Secoya/Ulloa Port -> LP 787-52/Tanner Orbital (score: 7375935.607518)
Start CR: 2,015,504,735
Hops    :          1
Jumps   :          1
Gain CR :  7,549,080
Gain/Hop:  7,549,080
Final CR: 2,023,053,815

  Load from Secoya/Ulloa Port (244ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y):
      760 x Metals/Gold   40,794cr vs   50,727cr, 7 days vs 1 hr, total: 31,003,440cr
  Unload at LP 787-52/Tanner Orbital (1.48Kls, BMk:Y, Pad:M, Plt:N, Flc:N, Shp:N, Out:Y, Ref:Y) => Gain 7,549,080cr (9,933cr/ton) => 2,023,053,815cr
  ----------------------------------------------------------------------------
Finish at LP 787-52/Tanner Orbital (1.48Kls, BMk:Y, Pad:M, Plt:N, Flc:N, Shp:N, Out:Y, Ref:Y) gaining 7,549,080cr (9,933cr/ton) => est 2,023,053,815cr total
```

As you can see, I got a different commodity than you, because the market data has changed.
In my case, Inara does not show TD's proposed buy station at all:
![image](https://user-images.githubusercontent.com/1733600/103591908-b9001b00-4eae-11eb-8f2d-b7a40fc2b45c.png)
![image](https://user-images.githubusercontent.com/1733600/103592480-6aec1700-4eb0-11eb-8f37-bcc801124d3c.png)

But if you search the system of TD's proposed station, you see that the station does show then:
![image](https://user-images.githubusercontent.com/1733600/103591970-e0ef7e80-4eae-11eb-8033-914929412806.png)

And while the price is different than shown in TD ( Ulloa Port \| Secoya 30,897 Cr ), (which may be a bug I need to look into), it is better than the best station ( Fullerton Terminal \| Corbenic 33,476 Cr ) with 760+ silver that is listed on Inara as shown in the first picture, so TD did indeed find the best trade.

Taking a look at Inara, I see that "Slatus/Hadifeld Station" isn't in the "Best Export" list for gold either, so it was probably the same in your case.

Inara doesn't seem to handle Fleet Carriers very well.

**Comment by eyeonus** [comment]
I should also mention Inara is showing different prices for commodities than TD is, for reasons I don't know.

TD pulls the live listings market data directly from EDDN, the network used to broadcast market data by programs like the Elite Dangerous Market Connector, and gets the rest from EDDB.io, which also gets its market data directly from EDDN, so I'm confident TD's data is correct.

I thought that Inara also got its market data from EDDN, so I've no idea why it has different prices, but again, this looks like Inara's fault.

**Comment by McRayJason** [comment]
Ok. I went ahead and just did a real scenario for checking the stuff up. This time i used EDDB.io to find a trade nearby.

![image](https://user-images.githubusercontent.com/39248367/103787973-9a308e80-503e-11eb-8bc3-ed7cea96e04f.png)

Ok so Bertrandite only 40ly from the selling point. Went there, and the prices were correct (eddb.io and real prices).
Went to sell it to Tanner Orbital, sold it for what eddb.io said.

I used the same filter for eddb.io and TD. But TD found something else, which was less profitable.

```
Command line: run --to="LP 787-52/Tanner Orbital" --cap=500 --cr=2015504735 --ly=50 --empty=50 --age=1 --direct --planetary=YN --pad=ML -vvv --progress
* Hop   1: .....6,803 origins 
 
Barathaona/Ejeta Dock -> LP 787-52/Tanner Orbital (score: 4776378.209974)
Start CR: 2,015,504,735
Hops    :          1
Jumps   :          1
Gain CR :  4,888,500
Gain/Hop:  4,888,500
Final CR: 2,020,393,235

  Load from Barathaona/Ejeta Dock (41ls, BMk:Y, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y):
      500 x Metals/Silver   30,530cr vs   40,307cr, 17 hrs vs 17 hrs, total: 15,265,000cr
  Unload at LP 787-52/Tanner Orbital (1.48Kls, BMk:Y, Pad:M, Plt:N, Flc:N, Shp:N, Out:Y, Ref:Y) => Gain 4,888,500cr (9,777cr/ton) => 2,020,393,235cr
  ----------------------------------------------------------------------------
Finish at LP 787-52/Tanner Orbital (1.48Kls, BMk:Y, Pad:M, Plt:N, Flc:N, Shp:N, Out:Y, Ref:Y) gaining 4,888,500cr (9,777cr/ton) => est 2,020,393,235cr total
```

I am really getting bit confused and don't know what to trust.

**Comment by eyeonus** [comment]
I'm not going to lie, I don't know. Maybe the market data on eddb.io was updated since the last time you ran an import on TD.

TD tries to account for the time different trade runs take. (Less time spent flying = more time making money)
Maybe the --ls-penalty , which makes a stations score lower the further it is from the arrival point, has something to do with it.

Do you look up the station data for Ramon Settlement in TD?

I don't know why, there are too many different variables that could cause the difference. Again, it's impossible for me to investigate your results because the market data changes constantly and when I ran the TD command you did I got a different route.

**Comment by McRayJason** [comment]
If by station data you mean Market, yes I did. And it saw the Bertrandite selling for 1615.
I ran it also on the Tanner Orbital, and got actually nothing for the buy, so that might be why it wasnt picked up by it.

Maybe because the actual station demand was 0, but when it is 0 you can in some cases still sell it in there, which eddb.io is aware off (not case for inara tho).

**Comment by McRayJason** [comment]
@eyeonus I am sorry to still be on this, but i have done some more testing and i tested like 5 direct trades from specific station to specific station and i never got a single trade with profit higher that 9,999cr/t. Could that be something? I found trades that are worth 24k cr/t on eddb.io, but TD showed only a trade that is below 10k cr/t.

Here is an example:
```
run --fr="HIP 98621/Herbig Terminal" --to="Turir/Brooks Terminal" --cap=700 --cr=2015504735 --ly=500.00 --empty=500.00 --direct --planetary=YN --pad=ML -vvv --progress
* Hop   1: .........1 origins 

                             
HIP 98621/Herbig Terminal -> Turir/Brooks Terminal (score: 6857527.965940)
Start CR: 2,015,504,735
Hops    :          1
Jumps   :          1
Gain CR :  6,462,400
Gain/Hop:  6,462,400
Final CR: 2,021,967,135

  Load from HIP 98621/Herbig Terminal (745ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y):
      700 x Metals/Cobalt    2,747cr vs   11,979cr, 11 hrs vs 1 hr, total:  1,922,900cr
  Unload at Turir/Brooks Terminal (42ls, BMk:N, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) => Gain 6,462,400cr (9,232cr/ton) => 2,021,967,135cr
  ----------------------------------------------------------------------------
Finish at Turir/Brooks Terminal (42ls, BMk:N, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) gaining 6,462,400cr (9,232cr/ton) => est 2,021,967,135cr total
```

![image](https://user-images.githubusercontent.com/39248367/104106367-657a3c80-52b5-11eb-8ed0-3ffbcef8f98f.png)

As you can see eddb.io showed two extra trades that are worth more than 10k, and the one that is 9,232cr/t
TD only shows the one that is 9,232cr/t

And this happened for all the trades i was looking randomly for that were above 10k profit on eddb.io

**Comment by eyeonus** [comment]
I have no idea, I didn't write the route finder code.

Fell free to have a look: https://github.com/eyeonus/Trade-Dangerous/blob/006b58b448ff915af2e33f73a8665de608d22144/tradedangerous/commands/run_cmd.py#L1111

**Comment by McRayJason** [comment]
Well i will be of no help in here, since i know nothing about the python and coding :(

**Comment by McRayJason** [comment]
I will be not much help with coding, but can it be something with this?
https://github.com/eyeonus/Trade-Dangerous/blob/006b58b448ff915af2e33f73a8665de608d22144/tradedangerous/commands/run_cmd.py#L160-L164 i see default set to 10000

tested to actually add something to the mgpt and got the correct results:

```
trade run --fr="HIP 98621/Herbig Terminal" --to="Turir/Brooks Terminal" --cap=700 --cr=2015504735 --ly=500.00 --empty=500.00 --mgpt=90000 --direct --planetary=YN --pad=ML -vvv --progress
* Hop   1: .........1 origins
HIP 98621/Herbig Terminal -> Turir/Brooks Terminal (score: 19663396.914466)
Start CR: 2,015,504,735
Hops    :          1
Jumps   :          1
Gain CR : 18,530,400
Gain/Hop: 18,530,400
Final CR: 2,034,035,135

  Load from HIP 98621/Herbig Terminal (745ls, BMk:N, Pad:M, Plt:N, Flc:N, Shp:N, Out:N, Ref:Y):
      700 x Metals/Gold   40,552cr vs   67,024cr, 13 hrs vs 2 hrs, total: 28,386,400cr
  Unload at Turir/Brooks Terminal (42ls, BMk:N, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) => Gain 18,530,400cr (26,472cr/ton) => 2,034,035,135cr
  ----------------------------------------------------------------------------
Finish at Turir/Brooks Terminal (42ls, BMk:N, Pad:L, Plt:N, Flc:N, Shp:Y, Out:Y, Ref:Y) gaining 18,530,400cr (26,472cr/ton) => est 2,034,035,135cr total
```

So looks like default is set to too low

**Comment by eyeonus** [comment]
Well, to be honest, that default was set long before Fleet Carriers were a twinkle in some dev's eyes. No idea why there is a max, but I imagine it has to do with lessening how long it takes to calculate potential routes.

Since most players can't afford Fleet Carriers and not many of those who do use them to conduct trading (as opposed to letting ships dock and trade with *them*), it makes sense to leave it as default, and you'll just have to remember to override the default when doing your FC-based trade runs.

Good job figuring it out, that is obviously the culprit.

**Comment by McRayJason** [comment]
Well its not only for FC trading. In general, 10k profit is too low. Even if you are doing like 20ly trade jump with your T10. I guess its because before, this high GPT was not really a thing, because commodities were much cheaper and the profit was never that high.

**Comment by eyeonus** [comment]
Right, yes, we're talking profit per ton, not profit as a whole, My mistake.

Okay, I found where it's used in the code:
(L818, L826)
https://github.com/eyeonus/Trade-Dangerous/blob/006b58b448ff915af2e33f73a8665de608d22144/tradedangerous/tradecalc.py#L803-L833

So it looks like this exists just to give the end-user the ability to specify the allowable profit margin range. As in, "I don't care about any trade that doesn't make at least 300/ton" = --min-gpt 300.

I assume when the default was originally set 10,000cr/ton was thought to be higher than any trade was likely to be, but rather than make the same mistake by guessing some higher "sensible" number, I'll just turn it off by setting the default to '0'.

Already pushed, should be able to update TD soon.
