### ISSUE TITLE
Argument --avoid and duplicate entries

### ISSUE THREAD

**Issue by Karmak23** [eyeonus/Trade-Dangerous#85]
See this error :

```
trade run --from "afli/pu" --to "phiagre/sopheos" --cap 56 --cr 6m --ly-per 20 --hops 5 --avoid Bhare/J8M-6VB                    
trade: System/Station "Bhare/J8M-6VB" could match Bhare/J8M-6VB or Bhare/J8M-6VB
```

Is is possible I have a duplicate in my database ? Could this come from the EDDBlink that is running since a few days ?

**Comment by eyeonus** [comment]
It's highly unlikely that you have a duplicate, but it is possible. You can check yourself using any SQLite database browser.

I myself use "[SQLite Database Browser](https://sqlitebrowser.org/dl/)" (Portable Version - no installation), but really any will do.

As far as it coming from EDDBlink, that's less likely, but not impossible, because the station you're trying to avoid is a fleet carrier, and those are finicky to deal with. You could try using '--fc N' if you want to avoid any and all fleet carriers, rather than the '--avoid ...' option, but that obviously doesn't fix the issue you discovered.

Stations and systems are stored according to their FDevID, which for stations is stored under the 'station_id' tag, and should be unique for every station, so not sure what's going on. Fleet Carrier 'names' should also be unique, as well, meaning no two fleet carriers should have the same ID *or* Name, ever.

I would need to get a copy of your database to check myself, it's basically everything in the /data folder.

I'd like you to zip up the data folder, and then do a 'clean' run of the eddblink plugin, and try that run again, see if the error pops up.

If it does, then upload the zipped folder to something, Google Drive is preferred, so I can look at it myself.

**Comment by gqgunhed** [comment]
Seems like related to my #90 ;-)

**Comment by eyeonus** [comment]
Indeed.
